general:
    minPlayers: 1
    secondsBeforeGameStarts: 60
    secondsAfterGameEnds: 30
    maxSecondsPerGame: 1800
    minX: -250
    maxX: 250
    minZ: -250
    maxZ: 250
games:
  'Iron Armor Set':
    goal:
    - iron_helmet:1
    - iron_chestplate:1
    - iron_leggings:1
    - iron_boots:1
  '5 Seeds':
    goal:
    - seeds:5
  '32 Dirt':
    goal:
    - dirt:32
  '32 Sand':
    goal:
    - sand:32
  'Furnace':
    goal:
    - furnace:1
  'Stone Sword':
    goal:
    - stone_sword:1