general:
    minPlayers: 1
    secondsBeforeGameStarts: 60
    secondsAfterGameEnds: 30
    maxSecondsPerGame: 1800
    minX: -500
    maxX: 500
    minZ: -500
    maxZ: 500
games:
  'Seeds':
    goal: seeds
  'Dirt':
    goal: dirt
  'Sand':
    goal: sand
  'Furnace':
    goal: furnace
  'Stone Sword':
    goal: stone_sword